// <auto-generated />
namespace VouterApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IntialDatabase2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialDatabase2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103111043546_IntialDatabase2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
